Task 8
ProgMiner/Lab_FormalLang pull request #7
Opened 2023-04-17 21:56 UTC by ProgMiner

- [x] Реализовать **функцию**, основанную на алгоритме Хеллингса, решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики.
  - Результат работы функции --- множество троек вида (вершина, нетерминал, вершина).
  - Предусмотрите возможность получать граф из различных источников в различных форматах.
  - Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).
  - Для преобразования грамматики в ОНФХ использовать результаты предыдущих работ.
- [x] На основе предыдущей функции реализовать функцию, позволяющую решать задачу достижимости для заданного набора стартовых и финальных вершин, и заданного нетерминала.
- [x] Добавить необходимые тесты.

2023-04-17 21:59 UTC, ProgMiner commented
Получение графа и грамматики из всевозможных источников поддержано путём перечисления способов их получения в документации. Городить обёртки для получения от туда и отсюда смысла нет никакого.

2023-04-18 09:59 UTC, rustam-azimov requested changes

2023-04-18 09:59 UTC, rustam-azimov commented on project/cfg.py
> +def hellings(graph: MultiDiGraph, cfg: CFG) -> set[tuple[int, Variable, int]]:
Все же добавьте union typing для случая, что передали граф и грамматику в строков виде, например для чтения из файла.

2023-04-18 12:10 UTC, ProgMiner commented on project/cfg.py
> +def hellings(graph: MultiDiGraph, cfg: CFG) -> set[tuple[int, Variable, int]]:
Сделал.

2023-04-24 10:33 UTC, rustam-azimov approved these changes

2023-04-24 10:36 UTC, merged